//
//  EntityViewController.swift
//  Animalia-ios
//
//  Created by Sebastian Soto Varas on 16/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class EntityViewController: UIViewController {
    
    private var currentStep: Int16?

    @IBOutlet weak var steps: StepLayer!
    // MARK: - Public properties -
    
    var detail: String?
    @IBAction func action(_ sender: Any) {
        steps.next()
    }
    
    @IBAction func back(_ sender: Any) {
        steps.back()
    }
    
    var presenter: EntityPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }
    
    private func setupUI() {
        steps?.delegate = self
        steps.start()
    }

}

// MARK: - Extensions -

extension EntityViewController: EntityViewInterface {
}

extension EntityViewController: StepLayerProtocol {
    func getCurrentStep(_ step: Int16) {
        self.currentStep = step
    }
}
