//
//  EntityPresenter.swift
//  Animalia-ios
//
//  Created by Sebastian Soto Varas on 16/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class EntityPresenter {

    // MARK: - Private properties -

    private unowned let view: EntityViewInterface
    private let interactor: EntityInteractorInterface
    private let wireframe: EntityWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: EntityViewInterface,
        interactor: EntityInteractorInterface,
        wireframe: EntityWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension EntityPresenter: EntityPresenterInterface {
}
