//
//  EntityInterfaces.swift
//  Animalia-ios
//
//  Created by Sebastian Soto Varas on 16/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol EntityWireframeInterface: WireframeInterface {
}

protocol EntityViewInterface: ViewInterface {
}

protocol EntityPresenterInterface: PresenterInterface {
}

protocol EntityInteractorInterface: InteractorInterface {
}
