//
//  RolePresenter.swift
//  Animalia-ios
//
//  Created by Sebastian Soto Varas on 28/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class RolePresenter {

    // MARK: - Private properties -

    private unowned let view: RoleViewInterface
    private let interactor: RoleInteractorInterface
    private let wireframe: RoleWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: RoleViewInterface,
        interactor: RoleInteractorInterface,
        wireframe: RoleWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension RolePresenter: RolePresenterInterface {
}
