//
//  RoleInteractor.swift
//  Animalia-ios
//
//  Created by Sebastian Soto Varas on 28/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class RoleInteractor {
}

// MARK: - Extensions -

extension RoleInteractor: RoleInteractorInterface {
}
