//
//  RoleInterfaces.swift
//  Animalia-ios
//
//  Created by Sebastian Soto Varas on 28/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol RoleWireframeInterface: WireframeInterface {
    func navigationToEntity()
}

protocol RoleViewInterface: ViewInterface {
}

protocol RolePresenterInterface: PresenterInterface {
    func startFlowEntity()
}

protocol RoleInteractorInterface: InteractorInterface {
}
