//
//  RoleWireframe.swift
//  Animalia-ios
//
//  Created by Sebastian Soto Varas on 28/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class RoleWireframe: BaseWireframe<RoleViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Role", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: RoleViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = RoleInteractor()
        let presenter = RolePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension RoleWireframe: RoleWireframeInterface {
    func navigationToEntity() {
        navigationController?.pushWireframe(EntityWireframe())
    }
}
