//
//  RoleViewController.swift
//  Animalia-ios
//
//  Created by Sebastian Soto Varas on 28/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class RoleViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: RolePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - Extensions -

extension RoleViewController: RoleViewInterface {
}
