//
//  RoleViewController.swift
//  Animalia-ios
//
//  Created by Sebastian Soto Varas on 28/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class RoleViewController: UIViewController {

    @IBOutlet weak var entity: CheckboxGroup!
    @IBOutlet weak var person: CheckboxGroup!
    
    @IBAction func tapEntity(_ sender: Any) {
        entity.actionSelected()
    }
    
    @IBAction func tapPerson(_ sender: Any) {
        person.actionSelected()
    }
    
    // MARK: - Public properties -

    var presenter: RolePresenterInterface!
    private var groupSelected: String?
    private var idSelected: String?

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    func setupView() {
        entity.delegate = self
        person.delegate = self
    }
    
    func setupSelect() {
        guard let group = self.groupSelected, let id = self.idSelected else { return }
        entity.selectStyleFor(group, id)
        person.selectStyleFor(group, id)
    }
}

// MARK: - Extensions -

extension RoleViewController: RoleViewInterface {
}

extension RoleViewController: CustomCheckboxGroupDelegate {
    func selectCheckbox(_ group: String, _ id: String) {
        self.groupSelected = group
        self.idSelected = id
        self.setupSelect()
    }
}
